version: '3.8'

services:
  # Base de datos MongoDB
  mongodb:
    image: mongo:6.0
    restart: always
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=control-callcenter
    networks:
      - app_network

  # Backend (API)
  backend:
    build: ./backend
    restart: always
    depends_on:
      - mongodb
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
      - PORT=4000
      - MONGODB_URI=mongodb://mongodb:27017/control-callcenter
      - JWT_SECRET=${JWT_SECRET:-tu-clave-secreta-fuerte-y-aleatoria}
      - CORS_ORIGIN=${CORS_ORIGIN:-http://localhost:80}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    volumes:
      - backend_logs:/app/logs
      - backend_uploads:/app/uploads
    networks:
      - app_network

  # Frontend
  frontend:
    build: ./frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "80:80"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  mongo_data:
  backend_logs:
  backend_uploads: 